### ISSUE TITLE
Errors throw on latest code version 

### ISSUE THREAD

**Issue by TornMarketing** [Webmecanik/plugin-grapesjs-builder#33]
Getting errors below on the latest code version 
although works fine for the packaged files 
https://github.com/Webmecanik/plugin-grapesjs-builder/releases/tag/1.0.0-beta

Mautic: v3.2.2
Ubuntu Cyberpanel Litespeed
PHP 7.3
```
Stack trace:
#0 /home/sub.domain.com.au/public_html/vendor/composer/ClassLoader.php(444): include()
#1 /home/sub.domain.com/public_html/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/sub.domain.com.au...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('MauticPlugin\\Gr...')
#3 [internal function]: spl_autoload_call('MauticPlugin\\Gr...')
#4 /home/sub.domain.com/public_html/app/AppKernel.php(186): class_exists('\\MauticPlugin\\G...')
#5 /home/sub.domain.com/public_html/vendor/symfony/http-kernel/Kernel.php(493): AppKernel->registerBundles()
#6 /home/sub.domain.com/public_html/app/AppKernel.php(242): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#7 /home/sub.domain.com/public_html/vendor/symfony/framework-bundle in /home/sub.domain.com/public_html/plugins/GrapesJsBuilderBundle/GrapesJsBuilderBundle.php on line 9
2020-12-28 05:07:47.547498 [NOTICE] [255.255.255.255:61027-Q:2E5BF853F0ADF0FC-17#sub.domain.com] [STDERR] Symfony\Component\Debug\Exception\FatalThrowableError: Class 'MauticPlugin\IntegrationsBundle\Bundle\AbstractPluginBundle' not found - in file /home/sub.domain.com/public_html/plugins/GrapesJsBuilderBundle/GrapesJsBuilderBundle.php - at line 9
```

**Comment by TornMarketing** [comment]
https://github.com/Webmecanik/plugin-grapesjs-builder/tree/mautic3x
