### ISSUE TITLE
My template is not loading...M3 and GrapeJS

### ISSUE THREAD

**Issue by weismannweb** [Webmecanik/plugin-grapesjs-builder#9]
cash.js:299 Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': 'sans",' is not a valid attribute name.
    at HTMLParagraphElement.<anonymous> (https://readers.rebeccagraceallen.com/plugins/GrapesJsBuilderBundle/Assets/js/grapes.min.js:3:3232)
    at w (https://readers.rebeccagraceallen.com/plugins/GrapesJsBuilderBundle/Assets/js/grapes.min.js:3:1237)
    at m.each (https://readers.rebeccagraceallen.com/plugins/GrapesJsBuilderBundle/Assets/js/grapes.min.js:3:4141)
    at m.attr (https://readers.rebeccagraceallen.com/plugins/GrapesJsBuilderBundle/Assets/js/grapes.min.js:3:3197)
    at m.attr (https://readers.rebeccagraceallen.com/plugins/GrapesJsBuilderBundle/Assets/js/grapes.min.js:3:3280)
    at r.updateAttributes (https://readers.rebeccagraceallen.com/plugins/GrapesJsBuilderBundle/Assets/js/grapes.min.js:2:67061)
    at renderAttributes (https://readers.rebeccagraceallen.com/plugins/GrapesJsBuilderBundle/Assets/js/grapes.min.js:2:68041)
    at render (https://readers.rebeccagraceallen.com/plugins/GrapesJsBuilderBundle/Assets/js/grapes.min.js:2:68112)
    at r.addToCollection (https://readers.rebeccagraceallen.com/plugins/GrapesJsBuilderBundle/Assets/js/grapes.min.js:3:63576)
    at https://readers.rebeccagraceallen.com/plugins/GrapesJsBuilderBundle/Assets/js/grapes.min.js:3:64069
(anonymous) @ cash.js:1
w @ cash.js:1
each @ cash.js:1
attr @ cash.js:1
attr @ cash.js:1
updateAttributes @ grapes.min.js:2
renderAttributes @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
addToCollection @ cash.js:1
(anonymous) @ cash.js:1
m.each.m.forEach @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
render @ cash.js:1
renderChildren @ grapes.min.js:2
render @ grapes.min.js:2
render @ Backbone.Undo.js:1
renderBody @ Backbone.Undo.js:1
I @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
(anonymous) @ grapes.min.js:2
load (async)
render @ Backbone.Undo.js:1
render @ Backbone.Undo.js:1
render @ Backbone.Undo.js:1
render @ Backbone.Undo.js:1
init @ Backbone.Undo.js:1
Mautic.initGrapesJS @ builder.js:247
Mautic.launchBuilder @ builder.js:42
onclick @ 20:1
trigger @ libraries.js?v9354bce3:683
(anonymous) @ libraries.js?v9354bce3:688
each @ libraries.js?v9354bce3:153
each @ libraries.js?v9354bce3:144
trigger @ libraries.js?v9354bce3:688
jQuery.fn.<computed> @ libraries.js?v9354bce3:796
buttonClick @ app.js?v9354bce3:73
dispatch @ libraries.js?v9354bce3:465
elemData.handle @ libraries.js?v9354bce3:451
Show 116 more frames

I am guessing this is an html validation issue?  with sans serif maybe?  Checking into it now but shouldn't it fail gracefully or is this a thing with grapejs that the html has to be perfect?

**Comment by weismannweb** [comment]
Yesh seems to be my custom template because the default neapolitan template shows fine.  Ill check things around any san serif declarations.  Also maybe I should run it through w3c validator?

**Comment by weismannweb** [comment]
So I got it to load....some weird issues with the html in the template we had:

`<p style="color: rgb(118, 123, 134); font-family: " open="" sans",="" sans-serif;="" font-size:="" 15px;="" line-height:="" 25px;"="">`

I am not sure if Mautic did that to my template or it was left over from our conversion from Mailchimp?

Anyway this may be a outlier and nothing anyone else would encounter.

**Comment by weismannweb** [comment]
closing this is it was an issue with my template
